# Generated by Django 3.1.2 on 2020-10-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_func', models.IntegerField(verbose_name='Matricula')),
                ('nome_func', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobre nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.IntegerField(max_length=12, verbose_name='Telefone')),
                ('contrato', models.CharField(choices=[('EA', 'EQUIPE AGEIS'), ('TD', 'TRANSFORMACAO DIGITAL'), ('CDS_SP', 'PMSP'), ('NC', 'NAO CRITICAS')], default='available', max_length=32)),
                ('data_admissao', models.DateField(verbose_name='Data Admissao')),
                ('data_entrega', models.DateField(verbose_name='Data da Entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.IntegerField(verbose_name='Patrimonio')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numeroserie', models.CharField(max_length=100, verbose_name='Numero de Serie')),
                ('especificacao', models.CharField(max_length=200, verbose_name='Especificacao')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situacao')),
            ],
        ),
    ]
