# Generated by Django 3.1.2 on 2020-10-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
