# Generated by Django 3.1.2 on 2020-10-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201023_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Patrimonio'),
        ),
    ]
