# Generated by Django 3.1.2 on 2020-10-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201023_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='user',
        ),
    ]
